#!/usr/bin/env bash

# Copyright 2025
# FireFleet Project
# SPDX-License-Identifier: Apache-2.0

# This script regenerates the CREDITS.md file based on the repository's
# contributors. Run it whenever new contributors join the project.
# Names and emails are normalized using .mailmap (if present).

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

{
    cat <<-'EOH'
# FireFleet Credits and Thanks

(This file is autogenerated using [update-credits.sh](tools/update-credits.sh).)

FireFleet is an open-source project that aims to simplify and orchestrate
Firecracker microVM clusters through a modular architecture consisting of
the FireFleet SDK, Agent, and Manager.

We thank all contributors who have helped design, build, improve, test,
document, and support the project.

Contributors to the FireFleet repository:
EOH
    echo
    git log --format='- %aN <%aE>' | LC_ALL=C.UTF-8 sort -uf | grep -v "dependabot"
} > CREDITS.md
